### ISSUE TITLE
[igValidator] Add an option to continue checking regardless of hit required or failed fields in the form

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/ignite-ui#1067]
### Description  
Enhance the igValidator to always run all rules and not stop at required or failed fields in the form. 

Add a new boolean option `validateAll` that forces the validator to process all rules and continue checking even when failed or required is hit.

**Comment by IG-Stanimir-Dimitrov** [comment]
@damyanpetev , `validateAll` must be settable for the global validator and also per field.

**Comment by damyanpetev** [comment]
Right, for the [multiple fields configuration](https://www.igniteui.com/help/igvalidator-overview#setting-up) scenario this should be available per-field for inheritance/overrides like so:
```js
$('#validationForm').igValidator({
  validateAll: true, //inherited
  fields : [{
      selector : "#password",
      required: true,
      lengthRange: { min: 8 }
    }, {
      selector : "#repeatParrword",
      required: true,
      equalTo : "#password",
      validateAll : false, //override
    }
    //...
  ]
});
```
Speaking of, "validate all" as a phrase is kinda conflicting with `validate()` itself when you have that fields collection. Maybe something like "run/executeAllRules"?
(I know, I know.. names keep getting longer)

**Comment by IG-Stanimir-Dimitrov** [comment]
@damyanpetev I suggest we go with `executeAllRules`

**Comment by damyanpetev** [comment]
@IG-Stanimir-Dimitrov I've updated the snippet above.
Adding more details for the original use case that prompted this enhancement:
The idea was to implement a conditional `required` validation through the `custom` function that depends on an external condition being met. Problem being that if required is not enabled, no further checks are executed. While it's possible to have the external condition alter the validatior options, depending on the scenario it might be required for the check to be self-contained.
So something like:
```js
$('#validationForm').igValidator({
  executeAllRules: true,
  fields: [
  //....
  {
    required: false,
    selector: "#lastName",
    custom: {
      method: function(value, fieldOptions){
        if(/* another field is not empty, conditions aren't met */){
          return false;
        }
        return true;
      },
      errorMessage : "This is required when <fieldX> is filled <and other conditions>."
    }
  },
  ]
});
```
This also ties in nicely with #1153.

### Empty values
Besides the `custom` check being allowed to on empty value as described above, this should still be considered a special case. I don't think any other rules make sense running without value as it interferes with the ability to define rules for an optional field.

### API interaction
Due to the fields collection most API descriptions' wording is already suitable for multiple messages and the only functional change I see would be [`getErrorMessages`](https://www.igniteui.com/help/api/2017.1/ui.igvalidator#methods:getErrorMessages) would return more than one error message even for one field.

**Comment by damyanpetev** [comment]
@IG-Stanimir-Dimitrov Updated above with event change - multiple `error` as those carry information about the rule that failed and makes sense. Usually the `success` is the counterpart of the `error`; however, I'm not sure there a case for kicking multiple success events.  Everything that didn't fail could be considered a success.

Maybe to separate rules that didn't run for empty value or a custom implementation of the "Multi-condition Info"?

**Comment by damyanpetev** [comment]
Discussing this with @kdinev, he made a good point that normally you'd expect a final event telling you what error(s) occurred rather than handling a bunch of error and success events. So that'd mean `error` and `success` still fire as they normally would but their arguments will need to change instead:

- `ui.rule: string` -> `ui.rules: string []`
- `ui.message: string` -> `ui.messages: string[]`
This will be a change to `success`, `error` and `validated` in general (regardless of the option).

That about right?

**Comment by IG-Stanimir-Dimitrov** [comment]
@damyanpetev so we are not changing the behavior, just the arguments of the events. I am ok with that.
