### ISSUE TITLE
The simple filtering editors have background color and the text is white in Superhero theme

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/ignite-ui#1273]
### Description  
The superhero theme changes the filtering editors  background to blue and respectively the text to being white.

### Steps to reproduce  

1. Open http://jsfiddle.net/n1q9mtpb/1/
2. Observe the simple filtering editors
3. Double click on a row
4. Observe the editors

### Result  
![editors](https://user-images.githubusercontent.com/3768136/31184931-66061ab8-a933-11e7-85a6-9e382b1483a6.jpg)

### Expected result  
![editors_expected](https://user-images.githubusercontent.com/3768136/31184936-6893ea26-a933-11e7-9bb9-41aad80e3c87.jpg)

The background of all editors should be white in order to be consistent across features.

If you start editing a row the editors there have a white background, thus the rest of the visible editors should also be white. Or maybe it should be fixed for the Updating editors?

**Comment by desig9stein** [comment]
I did that change on purpose, otherwise the filtering section look like the most important thing in the grid. It look like that, because of the theme contrast (dark, white). I think, if it's white, it take's too much of the attention from the grid content. 

When you editing a row, the editors have a white background, because the focus of user should be there, as obviously this is the current action that the user executes.

Keep in mind, that this is all my personal opinion and if necessary, I can revert the old behavior

**Comment by skrustev** [comment]
We do not have any other cases where what is being interacted on is contrasted heavily in this theme. The first example I can give see is the page size dropdown being white. In that case it should be dark as well.

The Updating is like that just because it has inputs which by default for the theme are white.
