### ISSUE TITLE
Numeric editors don't show the keypad after loosing focus on Firefox for Android

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/ignite-ui#1377]
### Description  
Once a numeric editor loses focus on Firefox for Android it will no longer show the numeric keypad

### Steps to reproduce  

1. Open the attached sample on an android device with firefox
2. Enter edit mode for the first editor (keypad appears)
3. Focus out (for example focus the second editor)
4. Try to edit the first one again

### Result  
The second time edit mode is entered the keypad is replaced with the normal keyboard

### Expected result  
The keypad should still be the way to enter values for the numeric editor after the first edit. Works fine on Chrome.

### Attachments  
[index.zip](https://github.com/IgniteUI/ignite-ui/files/1454266/index.zip)

**Comment by ChronosSF** [comment]
Briefly discussed with @damyanpetev . It seems browsers are happier now when the input has type="numeric" and this should probably be the way to create these editors going forward.

**Comment by ibrahimhubgit** [comment]
Hi,

I tested with 
@(Html.Infragistics().Columns(column =>
{
column.For(x => x.Quantite).DataType("numeric")"
})....

It's not working with FireFox

**Comment by ibrahimhubgit** [comment]
Why the type of input is "tel" and not "numeric" when the column is declaring to numeric editor ?

**Comment by SlavUI** [comment]
@ChronosSF @mpavlinov Hi guys is there an update on this one ?

**Comment by ChronosSF** [comment]
@SlavUI, imo this should be assigned to and addressed by @damyanpetev , @bazal4o or @Lipata  .

**Comment by Lipata** [comment]
@SlavUI, @ChronosSF we will work on this.

**Comment by SlavUI** [comment]
@Lipata and @ChronosSF  Thank you guys please provide an update on completion ;)

**Comment by kdinev** [comment]
@ibrahimhubgit When the numeric editor was developed, the only way to spawn the correct keyboard layout (numeric) on touch devices was to use `<input type="tel" />`. We can look into revising the `type` of the element if the current support on mobile browsers is up-to-date.

**Comment by bazal4o** [comment]
The issue is not related to the input type="tel", because the first time you focus the editor the numeric keypad is shown on my mobile phone. But after the first blur occurs every another focus of the editor is showing the alphabetical keyboard.
We should investigate if the issue is related to the browser, or it's coming from our code. 
The reason we are not using type number is we need to have extra css for removing the spin buttons which are automatically added by some browsers. And any new feature which is added by the browsers in terms of UI for type numeric should be excluded via css, or in code. With the type tel we receive both numeric validation and number keypad. But if the only solution is to replace the type with numeric - we add this enhancement.

**Comment by ViktorSlavov** [comment]
The issue is reproducible in **Firefox for Android** with a basic HTML input tag, without using any of the IG libraries. This is somehow related to the way Firefox handles dynamic input type change.
### Steps to reproduce:
1. Open the following [JSFiddle example](https://jsfiddle.net/nn6oL3qf/22/) in FireFox on mobile
2. Touch the input field (keypad appears)
3. Focus out of the input field.
4. Re-enter the input field.
The keyboard that does appear is the default one, not the keypad.
