### ISSUE TITLE
Clear Value icon in the Filter input.

### ISSUE THREAD

**Issue by sbozalieva** [IgniteUI/ignite-ui#1424]
### Description  

The Clear Filter function not visible at first look and is accessible tru clicking on the Filter Menu. The standards has changed and there is an easier way to clear/reset the filter described below. 

### Steps to reproduce  

1. Remove Clear Filter from the dropdownmenu 
![image](https://user-images.githubusercontent.com/23053821/33834664-548c686c-de8c-11e7-8de9-ab4cbbdcf9c4.png)

2. Add Clear Filter in the filter input field
![image](https://user-images.githubusercontent.com/23053821/33832704-cb24167a-de85-11e7-96bb-8019f62ed783.png)

### Result  
What is the actual result after following the steps to reproduce?
![image](https://user-images.githubusercontent.com/23053821/33834951-8515d508-de8d-11e7-8828-2a9a8ae1de9c.png)

### Expected result  
What is the expected result after following the steps to reproduce?
- As an user starts typing in the input field on input symbol, a Clear Value icon appears .
- If an user clicks on the Clear Value icon, the field is cleared and the Clear Value Icon disappears.

**Comment by kacheshmarova** [comment]
When the field in the underlying data source is of a type: string and number the 'Clear' button will appear when the user starts typing.
When the field in the underlying data source is of a type: date the 'Clear button is not going to be visible since we need to render drop-down button which opens the date picker
PR:
http://tfs3.infragistics.local:8080/tfs/engineering/NetAdvantage/NetAdvantage%20Team/_git/ignite-ui/pullrequest/2559?_a=overview
