### ISSUE TITLE
Dropdown calendar does not close when its parent dialog is closed.

### ISSUE THREAD

**Issue by bazal4o** [IgniteUI/ignite-ui#1610]
Dropdown calendar does not close when its parent dialog is closed.
TFS#249359

### Steps to reproduce  
1) Run the attached sample (CASE-28597T_.zip).

2) Click the dropdown button on the editor.

3) Move the dialog window by dragging the title bar.
4) Click the close button on the dialog’s title bar.

### Result  
Dropdown calendar remains opened.

### Expected result  
Dropdown calendar should close when a dialog’s title bar is clicked.

### Attachments  
Sample: 
[CASE-28597T_.zip](https://github.com/IgniteUI/ignite-ui/files/1741246/CASE-28597T_.zip)

**Comment by bazal4o** [comment]
The issue was originally submitted for the igDatePicker - but the core of the problem is preventing default events like mouse move or click to the body of the document which will automatically close the picker. 
Note! 
The issue is reproducible with jQuery UI Datepicker too.

**Comment by ViktorSlavov** [comment]
A workaround was provided to the client:

  $("#dialog").igDialog({
...
   blur : function(evt, ui) {
     $("#datePicker").igDatePicker("hideDropDown");
   }
  });

This bug occurs due to specific interaction between igDialog and igDatePicker (based on jQuery UI datepicker) and introducing a fix may cause more problems and impact existing functionality. That is why we would rather provide the fix above.
