### ISSUE TITLE
igDatePicker is throwing error, when dataMode is set to displayModeText

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/ignite-ui#1733]
### Description  
igDatePicker is throwing error, when dataMode is set to displayModeText and dateInputFormat is set to "yyyy-MM-dd"

### Steps to reproduce  

1. Open the [following demo](https://jsfiddle.net/Lipata/Lbaxb8fd/2/)
2. Open the drop down
3. Select a data

### Result  
The drop down is not closed and there is an exception:
Cannot read property 'toString' of null

### Expected result  
No error is thrown, drop down is closed and date is selected.

Note that this is working in 18.1 and 18.2

**Comment by damyanpetev** [comment]
It seems the issue is caused by a combination of the different format the jQuery UI datepicker applies back to the input (worked around in latest source) and older date formatting (17.2+ handles `Invalid Date` gracefully).

This can be verified easily by setting the picker format to match:
```js
datepickerOptions: {
  dateFormat: "yy-mm-dd"
}
```
Which should cause the editor to behave as expected: https://jsfiddle.net/damyanpetev/Lbaxb8fd/5/

I'll move the text override from master to avoid the need for adding secondary format like above.
