### ISSUE TITLE
Latest SR npm package is missing

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/ignite-ui#1772]
### Description  
The 18.1.55 build is not available as an NPM package. The deployment has failed due to the token revocation that happened recently for all npmjs accounts.

**Comment by damyanpetev** [comment]
@kdinev Yeah, make that package*s*.
Already updated for #1764 but those came in after the SR's were tagged. Either way, affected releases will need to be re-tagged.

**Comment by damyanpetev** [comment]
Fair enough, I see changes after the tags anyway so manual publish it is.
The following are now available:
- https://www.npmjs.com/package/ignite-ui/v/18.1.56 (which is [18.1.55](https://www.npmjs.com/package/ignite-ui/v/18.1.55) with bumped version due to https://github.com/npm/www/issues/89)
- https://www.npmjs.com/package/ignite-ui/v/17.2.538
- https://www.npmjs.com/package/ignite-ui/v/17.1.2082
