### ISSUE TITLE
igScroll does not allow scrolling via touch in mixed environment on IE, Edge and FireFox.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/ignite-ui#180]
igScroll does not allow scrolling via touch in mixed environment on IE, Edge and FireFox.
Seems to work only on Chrome at the moment.

**Comment by skrustev** [comment]
Currently touch events are not supported on Firefox 24.0 and up for desktop/mixed environment. Mobile devices shouldn't be affected. Links:
https://developer.mozilla.org/en-US/docs/Web/API/Touch_events

**Comment by kdinev** [comment]
Closing issue as a third-party issue. 

"As of Gecko 24.0 (Firefox 24.0 / Thunderbird 24.0 / SeaMonkey 2.21), the touch events support introduced with Gecko 18.0 (Firefox 18.0 / Thunderbird 18.0 / SeaMonkey 2.15) has been disabled on the desktop version of Firefox (bug 888304), as some popular sites including Google and Twitter were not working properly. Once the bug is fixed, the API will be enabled again. To enable it anyway, open `about:config` and set the `dom.w3c_touch_events.enabled` preference to `2`. "
