### ISSUE TITLE
igDatePicker calendar falls back to default regional settings when 'en-US' is passed

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/ignite-ui#1842]
### Description  
The `regional` option on the `igDatePicker` applies regional settings to the underlying jQuery UI date picker as well. However, when 'en-US' the control sets the `$.ig.util.regional` instead, which is the default regional and can be any valid one (in this case Japanese). This can cause the calendar to display in a different regional from the set option.

This is caused by changes for https://github.com/IgniteUI/ignite-ui/issues/1358

### Steps to reproduce  

1. Run the attached sample
2. Select en-US regional
3. Open the date picker

### Result  
Calendar displayed in Japanese

### Expected result  
Calendar should display with en settings.

### Attachments  
[CAS-30288-Sample5.zip](https://github.com/IgniteUI/ignite-ui/files/2599572/CAS-30288-Sample5.zip)

**Comment by ViktorSlavov** [comment]
@damyanpetev 
This is occurring because of the explicit check for `this.options.regional === 'en-US'` ([link](https://github.com/IgniteUI/ignite-ui/blob/master/src/js/modules/infragistics.ui.editors.js#L11132)).
However, the check is necessary for the fix for #1358, as the default value for `regional` is `en-US` (inherited from widget component) ([link](https://github.com/IgniteUI/ignite-ui/blob/master/src/js/modules/infragistics.ui.widget.js#L85)).
We can approach the fix for this a couple of ways - we can either override the inherited value for `regional` in the `baseEditor` class (fixing the issue for all editors, but not for other controls) **OR** we can change the default value of `regional` for the `widget` class to `defaults` (fixing the issue for all controls, but overriding existing behavior). The latter seems to be a more correct approach (as there is always a 'defaults' property set in the regional object) ([link](https://github.com/IgniteUI/ignite-ui/blob/master/src/js/modules/infragistics.util.js#L250))
