### ISSUE TITLE
Create knockout binding handler for igTimePicker

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/ignite-ui#1885]
### Description  
There should be knockout binding handler for igTimePicker similar to the other editors.

**Comment by TammyD79** [comment]
This issue is blocking me from implementing the control due to our current architecture using knockout binding with the DatePicker. We have had a lot of customer complaints due to how the time works with the DateEditor. it doesn't work very smooth with the calendar turned on so we need this fix ASAP so that we can split the control up and provide a better experience.
