### ISSUE TITLE
When the direction of the popover is left, it should show up from that direction, even though there is not enough space

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/ignite-ui#637]
[popover.zip](https://github.com/IgniteUI/ignite-ui/files/642610/popover.zip)

**Comment by ChronosSF** [comment]
Actually I don't think we should touch this. The code in question does two things:

First it ensures the popover would not appear @ negative coordinates, then if it would it doesn't show it to the *left* at all because pushing it to the right to disallow negative coordinates would make it overlap the container it's showing for. So the question here is if we should take user-defined direction as a gospel and never do any checks for applicability _or_ we keep it as it is and still do the traversal of the priority array. 

On a side note *top* doesn't use *left*'s code and actually shows at negative coordinates so we have to at least make the two consistent whatever we decide. *bottom* and *right* currently cause page scrollbars in these cases which may or may not be desirable either.

The consensus we had with Deyan on the matter is that ultimately user specified direction is kind of pointless to try and improve as a scenario. We should instead expose the priority array as a public option and allow users only to specify in which order we have to check for enough space. Then we just have to decide what we do if there is literally no space to either direction, which should be an easy choice.

@kdinev , @IG-Stanimir-Dimitrov what do you think? Should we take user-specified direction absolutely and show the popover there even if it causes it to show @ negative coordinates ?

**Comment by IG-Stanimir-Dimitrov** [comment]
I agree that having flexible direction options and predefined auto priority is counter logical and even confusing for Clients.

The correct change to me would be to (1) keep the direction options as they are (and currently used by Clients), (2) force the _left_ popover to overlap the container if absolutely required and (3) let people set programmatically the priority direction for _auto_. Btw, even now the popover shows from _left_ and overlaps the container in _auto_ when there is not enough space in any direction.

**Comment by ChronosSF** [comment]
I think _left_ works like this because it's last in the priority array and the control prefers to show a popover somehow so when it reaches _left_ and there is still no space it goes through a different logic flow to basically have it appear somewhat properly.

So to summarize:

1. We disallow negative positioning but instead prefer overlapping the container. As a side note to that, do we prefer overlapping over creating page scrollbars?
2. User-defined direction is to be used always even if it causes said overlap.
3. We expose an additional option which is an array of strings called directionPriority (any feedback about the name?). With direction "auto" the control will go through the array and attempt to position at each string matching _left_, _right_, _top_ or _bottom_ disregarding non-matching strings. If neither recognized direction produces a positive result we show the popover at the bottom (since this is the direction with highest internal priority currently) using the rule in 1.
