### ISSUE TITLE
[igPercentEditor] The value is incremented by 1 when the isLimitedToListValues is set to true

### ISSUE THREAD

**Issue by agicheva** [IgniteUI/ignite-ui#657]
**Steps to reproduce**
Open the following sample:
http://jsfiddle.net/8j5wxywu/
Select value from the dropdown and spin up/down 

**Actual result**
The value is incremented/decremented by 1.

**Expected result**
The value is supposed to be the previous/next element from the listItems. 

**Comment**
It is reproducible for igNumericEditor and igPercentEditor.

**Comment by IG-Stanimir-Dimitrov** [comment]
As discussed, the expected behaviour is follows:

- `isLimitedToListValues: true` forces the spinner to go only though listed values
   * the array is not sorted so the spinner goes through the numeric values as listed (may not be in ascending order)
  * spinDelta is ignored
  * when dropdown list is open, the spinner buttons let users go through the list
- `isLimitedToListValues: false`  lets the spinner increment/decrement the editor value by the spinDelta
- `isLimitedToListValues: true, revertIfNotValid: true` reverts the editor value to the last valid number from the list, e.g. spin up to 20 and type in 21, on blur the editor sets value back to 20
-  `buttonType: "clear", isLimitedToListValues: true` still lets the user clear the value back to 0. However, if 0 is not among the listed values, the tooltip warns about that.
