### ISSUE TITLE
Editor looses focus in IE 11 when you have a notifier attached to it.

### ISSUE THREAD

**Issue by Marina-L-Stoyanova** [IgniteUI/ignite-ui#661]
**Steps to reproduce:**
Open the attached sample in IE11.
Try to focus the editor.

**Actual results:**
The control loses focus automatically and the notification closes.

**Expected result:**
The user should be allowed to focus the editor. 

[igNotifier.zip](https://github.com/IgniteUI/ignite-ui/files/649354/igNotifier.zip)

**Comment by dkamburov** [comment]
The igNotifier expects its target to be focusable. As it turns out IE is messing up the focus when the target is the DIV on which igNotifier is initialized. So we have to use the INPUT(as a focusable element) of the editor to initialize igNotifier.

[igNotifier.zip](https://github.com/IgniteUI/ignite-ui/files/686836/igNotifier.zip)
