### ISSUE TITLE
igZoombar buttons not visible with a bootstrap theme

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/ignite-ui#678]
https://github.com/IgniteUI/igniteui-angular2/issues/119

**Comment by MayaKirova** [comment]
This is actually not an issue with the bootstrap classes. 
It occurs when the bootstrap.js file is referenced on the page, because it contains a function with the name "button" that conflicts with JQuery UI's button, which we internally use to create the buttons: 
http://stackoverflow.com/questions/26180429/jquery-ui-and-bootstrap-button-conflict

This appears to be a third party issue.
I'm attaching an isolated sample for future reference. 
[sample.zip](https://github.com/IgniteUI/ignite-ui/files/669135/sample.zip)

**Comment by mpavlinov** [comment]
Closing it as "Third-Party-Issue".
